version: "3.8"
services:

  # Swarm Bee
  bee:
    hostname: bee
    image: ethersphere/bee:0.6
    restart: unless-stopped
    environment:
      - BEE_FULL_NODE=true
      - BEE_PASSWORD=psw
      - BEE_SWAP_ENDPOINT=<change_me>
    restart: unless-stopped
    networks:
      - bee-net
    ports:
      - 1633:1633 # gateway api
      - 1634:1634 # p2p
    volumes:
      - bee-data:/home/bee/.bee
    command: start
    
  # FairOS-dfs
  dfs-server:
    image: etherna/fairos-dfs:0.6-pre
    volumes:
      - dfs-server-data:/go/fairOS-dfs/dist/data
    depends_on:
      - bee
    restart: unless-stopped
    networks:
      - bee-net
    ports:
      - 9090:9090
    entrypoint: [ "/go/fairOS-dfs/dist/dfs", "server", "--beeHost", "bee", "--beePort", "1633", "--dataDir", "/go/fairOS-dfs/dist/data" ]
    
  # Mongo
  mongo:
    hostname: mongo
    image: mongo:4.4
    volumes:
      - mongo-db-data:/data/db
      - mongo-configdb-data:/data/configdb
    networks:
      - mongo-net
    ports:
      - 27017:27017
    restart: unless-stopped
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all" ]
    
  # Etherna SSO
  
  # Etherna Index
  
  # Etherna Credit
  
  # Etherna Dapp
  
  # FairOS-dfs file explorer
    
    
networks:
  bee-net:
  mongo-net:
      
volumes:
  bee-data:
  dfs-server-data:
  mongo-db-data:
  mongo-configdb-data:
