version: "3.8"
services:

  # Swarm Bee
  bee:
    hostname: bee
    image: ethersphere/bee:0.6
    restart: unless-stopped
    environment:
      - BEE_FULL_NODE=true
      - BEE_PASSWORD=psw
      - BEE_SWAP_ENDPOINT=<change_me>
    restart: unless-stopped
    networks:
      - bee-net
    volumes:
      - bee-data:/home/bee/.bee
    command: start
    
  # FairOS-dfs
  dfs-server:
    image: etherna/fairos-dfs:master
    volumes:
      - dfs-server-data:/go/fairOS-dfs/dist/data
    depends_on:
      - bee
    restart: unless-stopped
    networks:
      - bee-net
    ports:
      - 9090:9090
    entrypoint: [ "/go/fairOS-dfs/dist/dfs", "server", "--beeHost", "bee", "--beePort", "1633", "--dataDir", "/go/fairOS-dfs/dist/data" ]
  
  # FairOS-dfs file explorer
    
    
networks:
  bee-net:
      
volumes:
  bee-data:
  dfs-server-data:
