version: "3.8"
services:

  # Swarm Bee
  bee:
    hostname: bee
    image: ethersphere/bee:0.6
    environment:
      - BEE_FULL_NODE=true
      - BEE_PASSWORD=psw
      - BEE_SWAP_ENDPOINT=<change_me>
      ## cache capacity in chunks, multiply by 4096 to get approximate capacity in bytes
      - BEE_CACHE_CAPACITY=250000

    restart: unless-stopped
    networks:
      - bee-net
    volumes:
      - bee-data:/home/bee/.bee
    command: start

  # FairOS-dfs
  dfs-server:
    image: etherna/fairos-dfs:master
    volumes:
      - dfs-server-data:/go/fairOS-dfs/dist/data
    depends_on:
      - bee
    restart: unless-stopped
    networks:
      - bee-net
    ports:
      - 9090:9090
    entrypoint: [ "/go/fairOS-dfs/dist/dfs", "server", "--beeHost", "bee", "--beePort", "1633", "--dataDir", "/go/fairOS-dfs/dist/data" ]

networks:
  bee-net:

volumes:
  bee-data:
  dfs-server-data:
